### ISSUE TITLE
Unable to recreate logo

### ISSUE THREAD

**Issue by timlai4** [zY2EZHVByG/Logo2PWM#3]
I am attempting to extract the PWM for a logo using your tool. 
![tileshop](https://user-images.githubusercontent.com/46388504/96657717-ee19ba00-1310-11eb-9e23-9c4a1ebf130f.jpg)

When I try to run Logo2PWM, the new generated logo looks like:
```
>> f_logo_to_PWM_publish('tileshop.jpg', "24")
has Y axis? -- 0
has X axis? -- 0
```
![tileshop_rg_logo](https://user-images.githubusercontent.com/46388504/96657724-f245d780-1310-11eb-9384-a7e5aac0ae46.png)
I noticed that it does not seem to be detecting the Y-axis. There was a different motif that was formatted very similarly to this one, which the program did a much better job predicting, despite also being unable to detect the Y-axis. That motif was only 8 characters long. 

I had a look at several of the example logos, and they all seem to be much shorter than 24. Moreover, running those did detect both coordinate axes. 

Can you offer some insight as to why this logo is performing so badly?

**Comment by zY2EZHVByG** [comment]
Hi there, I have improved the image processing algorithm and the result for
these type of logos has been improved:
[image: image.png]

Your sample logo image has a low resolution and each letter is tightly
close (or even overlap) to its left and right neighbors, which is very
challenging for the app. I am still trying to find a better solution for
it.

For now, please try:

   - Manually crop the logo image and keep only the pure logo
   - Manually revise the output matrix for correct result
   - Use higher resolution logo images


Thank you so much for your input!

**Comment by zY2EZHVByG** [comment]
Hi @timlai4, please pull the most recent update to try the improved version. The current result for your sample image looks like this:
 
![test](https://user-images.githubusercontent.com/1680955/96841946-08878c80-1412-11eb-8b56-13654a2929c1.png)

**Comment by timlai4** [comment]
Thank you for your response. 

> Your sample logo image has a low resolution and each letter is tightly
close (or even overlap) to its left and right neighbors, which is very
challenging for the app. I am still trying to find a better solution for
it.

I tested the program initially with a higher resolution for the image which did not seem to perform any better. Here is the higher resolution image.
![gkq217f4](https://user-images.githubusercontent.com/46388504/97059400-53161f80-155e-11eb-9545-f0d20cb5ea78.jpg)

> - Manually crop the logo image and keep only the pure logo

I also tried this. I don't have the original image anymore, but since it didn't seem to be able to detect the axes, I tried just cropping them out entirely so we only have the motif. Unfortunately, this performed even worse: the program seem to become very confused. When I did not specify that there should be 24 letters, it only printed out three letters. When I specified there should be 24 letters, it printed out 24 spaces but all the spaces were blank. 

The most recent update looks greatly improved. However, the reason I am attempting to use the converter instead of specifying the PWM as a consensus motif with 1's and 0's is that I'd like to capture some of the small but still visible ambiguity, especially on position 4. The last five positions, where your new version still suffers, does not have any visible ambiguity, so I'd hope the program would predict 1's there.

**Comment by zY2EZHVByG** [comment]
Hi @timlai4, please update the newest code, and the accuracy has been improved a lot. 
![Screenshot 2020-10-28 215021](https://user-images.githubusercontent.com/1680955/97519695-a4138280-1967-11eb-843f-ca386d33d91f.png)
Above it is the regenerated logo image for your reference. 

Yes, the feature of auto-detecting the n count is not stable enough. 

Thanks for your feedback!
